name: "Build MinkowskiEngine"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  Build-TMC13:
    # see also https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # see https://github.com/Jimver/cuda-toolkit/blob/master/src/links/linux-links.ts
        cuda_version: [12.1.0, 11.7.1]
        gcc_version: [8, 10]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cuda
        uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: ${{matrix.cuda_version}}

      - name: Setup conda envirionment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false

      - name: Install python package
        run: source .github/workflows/install_py_pkg.sh ${{ github.workspace }} ${{matrix.cuda_version}} ${{matrix.gcc_version}}
