name: "Build MinkowskiEngine"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  Build-MinkowskiEngine:
    # see also https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # see https://github.com/Jimver/cuda-toolkit/blob/master/src/links/linux-links.ts
        python-version: [3.10]
        gcc_version: [8, 9, 10]
        include:
          - cuda_version: 11.7
            cuda_short_version: 117

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{matrix.python-version}}

      - name: Manually install conda pacakges
        shell: bash -el {0}
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cu${{matrix.cuda_short_version}}
          conda install -y cudatoolkit=${{matrix.cuda_version}} pytorch-cuda=${{matrix.cuda_version}} -c pytorch -c nvidia
          conda install -y -c conda-forge cudatoolkit-dev=${{matrix.cuda_version}} gcc=${{matrix.gcc_version}} gxx=${{matrix.gcc_version}}
          conda install -y -c anaconda openblas-devel
          conda info
          conda list

      - name: Build
        shell: bash -el {0}
        run: |
          cd ${{github.workspace}} && python setup.py install '--blas_include_dirs=${CONDA_PREFIX}/include' --blas=openblas --force_cuda
