name: "Build MinkowskiEngine"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  Build-MinkowskiEngine:
    # see also https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # see https://github.com/Jimver/cuda-toolkit/blob/master/src/links/linux-links.ts
        include:
          - cuda_version: 11.7
            cuda_version_short: 117
            gcc_version: 8
          - cuda_version: 11.7
            cuda_version_short: 117
            gcc_version: 9
          - cuda_version: 11.7
            cuda_version_short: 117
            gcc_version: 10
             

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare conda environment file
        run: |
          sed -i 's/CUDA_VERSION/${{matrix.cuda_version}}/g' ${{github.workspace}}/.github/environment.yml
          sed -i 's/GCC_VERSION/${{matrix.gcc_version}}/g' ${{github.workspace}}/.github/environment.yml
          sed -i 's/CUDA_VERSION_SHORT/${{matrix.cuda_version_short}}/g' ${{github.workspace}}/.github/environment.yml
          cat ${{github.workspace}}/.github/environment.yml

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mink
          environment-file: .github/environment.yml
          auto-activate-base: false

      - name: Build
        shell: bash -el {0}
        run: |
          conda info
          conda list
          cd ${{github.workspace}} && python setup.py install '--blas_include_dirs=${CONDA_PREFIX}/include' --blas=openblas --force_cuda
